#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/opt/bin/eww -c $HOME/.config/my_bar"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
				album_art
        
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww && bspc config -m LVDS-1 top_padding 10
else
	${EWW} close-all && killall eww && run_eww && bspc config -m LVDS-1 top_padding 10
fi
